######################## default configuration ####################
baseURL = "https://unf-montreal.ca/"
title = "unf-montreal.ca"
theme = "educenter"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
# [[Languages.fr.menu.main]]
# name = 'Accueil'
# URL = '/'
# weight = 1

[[Languages.fr.menu.main]]
name = 'À propos de nous'
URL = 'about'
weight = 1
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Notre équipe"
  URL = "team"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Nos chercheurs"
  URL = "researchers"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Notre histoire"
  URL = "history"
  weight = 3

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Contact"
  URL = "contact"
  weight = 4

[[Languages.fr.menu.main]]
weight = 2
name = "Installations"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "IRM"
  URL = "documentation/facility/mri"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "Salle de simulation"
  URL = "documentation/facility/simulation_room"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "Salle de tests"
  URL = "documentation/facility/testing_room"
  weight = 3

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "Matériels et logiciels"
  URL = "documentation/facility/hardware_software"
  weight = 4

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "EEG (bientôt)"
  URL = "documentation/facility/eeg"
  weight = 5

  [[Languages.fr.menu.main]]
  parent = "Installations"
  name = "Calendrier de réservation"
  URL = "https://reservation.unf-montreal.ca/Web/index.php?"
  weight = 6

[[Languages.fr.menu.main]]
name = "Nouvelles"
hasChildren = true
weight = 3

  [[Languages.fr.menu.main]]
  parent = "Nouvelles"
  name = "Nouvelles récentes"
  URL = "news"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Nouvelles"
  name = "Séminaires"
  URL = "seminars"
  weight = 2

[[Languages.fr.menu.main]]
weight = 4
name = "Votre étude"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Éthique"
  URL = "documentation/welcome/ethic"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Consignes de sécurité"
  URL = "documentation/welcome/safety_guidelines"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Préparez votre étude IRM"
  URL = "documentation/your_study/setup_mri"
  weight = 3

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Préparez votre étude EEG"
  URL = "documentation/your_study/setup_eeg"
  weight = 4

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Réservation"
  URL = "https://reservation.unf-montreal.ca/Web/schedule.php"
  weight = 5

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Formulaires et documents"
  URL = "document"
  weight = 6

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Téléchargement de vos données IRM"
  URL = "documentation/your_data/download_data"
  weight = 7

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Prétraitement de vos données"
  URL = "documentation/your_data/preproc_data"
  weight = 8

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Découvertes fortuites"
  URL = "documentation/your_study/finding"
  weight = 9

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Logos"
  URL = "document/logos"
  weight = 10

  [[Languages.fr.menu.main]]
  parent = "Votre étude"
  name = "Taux horaire"
  URL = "rate"
  weight = 11

[[Languages.fr.menu.main]]
weight = 5
name = "Formations"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Formation à la sécurité en IRM"
  URL = "course/safety_training"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Stockage de vos données"
  URL = "documentation/your_data/data_storage"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Analyse de vos données"
  URL = "documentation/your_data/data_analysis"
  weight = 3

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Compute Canada"
  URL = "course/compute_canada"
  weight = 4

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Globus"
  URL = "course/globus"
  weight = 5

  [[Languages.fr.menu.main]]
  parent = "Formations"
  name = "Documentation"
  URL = "documentation"
  weight = 6

## English Menu
[[menu.main]]
name = "About us"
URL = "about"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "About us"
  name = "Our team"
  URL = "team"
  weight = 1

  [[menu.main]]
  parent = "About us"
  name = "Our researchers"
  URL = "researchers"
  weight = 2

  [[menu.main]]
  parent = "About us"
  name = "UNF History"
  URL = "history"
  weight = 3

  [[menu.main]]
  parent = "About us"
  name = "Contact"
  URL = "contact"
  weight = 4

[[menu.main]]
weight = 2
name = "Facility"
hasChildren = true

  [[menu.main]]
  parent = "Facility"
  name = "MRI"
  URL = "documentation/facility/MRI"
  weight = 1

  [[menu.main]]
  parent = "Facility"
  name = "Simulation room"
  URL = "documentation/facility/simulation_room"
  weight = 2

  [[menu.main]]
  parent = "Facility"
  name = "Testing room"
  URL = "documentation/facility/testing_room"
  weight = 3

  [[menu.main]]
  parent = "Facility"
  name = "MRI hardware & software"
  URL = "documentation/facility/hardware_software"
  weight = 4

  [[menu.main]]
  parent = "Facility"
  name = "EEG (coming soon)"
  URL = "documentation/facility/EEG"
  weight = 5

  [[menu.main]]
  parent = "Facility"
  name = "Reservation calendar"
  URL = "https://reservation.unf-montreal.ca/Web/schedule.php"
  weight = 6

[[menu.main]]
name = "News"
hasChildren = true
weight = 3

  [[menu.main]]
  parent = "News"
  name = "Recent news"
  URL = "news"
  weight = 1

  [[menu.main]]
  parent = "News"
  name = "Seminars"
  URL = "seminars"
  weight = 2

[[menu.main]]
weight = 4
name = "Your study"
hasChildren = true

  [[menu.main]]
  parent = "Your study"
  name = "Ethics"
  URL = "documnentation/welcome/ethic"
  weight = 1

  [[menu.main]]
  parent = "Your study"
  name = "Safety guidelines"
  URL = "Safety guidelines"
  weight = 2

  [[menu.main]]
  parent = "Your study"
  name = "Setting up you MR study"
  URL = "documentation/your_study/setup_mri"
  weight = 3

  [[menu.main]]
  parent = "Your study"
  name = "Setting up your EEG study"
  URL = "documentation/your_study/setup_eeg"
  weight = 4

  [[menu.main]]
  parent = "Your study"
  name = "Reservation"
  URL = "https://reservation.unf-montreal.ca/Web/schedule.php"
  weight = 5

  [[menu.main]]
  parent = "Your study"
  name = "Forms and documents"
  URL = "document"
  weight = 6

  [[menu.main]]
  parent = "Your study"
  name = "MRI data download"
  URL = "documentation/your_data/download_data"
  weight = 7

  [[menu.main]]
  parent = "Your study"
  name = "Data preprocessing"
  URL = "documentation/your_data/preproc_data"
  weight = 8

  [[menu.main]]
  parent = "Your study"
  name = "Incidental findings"
  URL = "documentation/your_study/finding"
  weight = 9

  [[menu.main]]
  parent = "Your study"
  name = "Logos"
  URL = "document/logos"
  weight = 10

[[menu.main]]
name = "Training"
hasChildren = true
weight = 5

  [[menu.main]]
  parent = "Training"
  name = "MRI safety training"
  URL = "course/safety_training"
  weight = 1

  [[menu.main]]
  parent = "Training"
  name = "Data storage"
  URL = "documentation/your_data/storage_data"
  weight = 2

  [[menu.main]]
  parent = "Training"
  name = "Data analysis"
  URL = "documentation/your_data/analysis_data"
  weight = 3

  [[menu.main]]
  parent = "Training"
  name = "Compute Canada"
  URL = "course/compute_canada"
  weight = 4

  [[menu.main]]
  parent = "Training"
  name = "Globus"
  URL = "course/globus"
  weight = 5

  [[menu.main]]
  parent = "Training"
  name = "Documentation"
  URL = "documentation"
  weight = 6


# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"

enableGitInfo = true

#################### default parameters ################################
[params]
logo = "images/logo_unf.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "4565 Queen Mary Rd, Montreal, QC H3W 1W5"
mobile = "514-340-3540 ext. 3633"
email = "support.unf@criugm.qc.ca"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true


##################### DOCSY #####################
# Everything below this are Site Params

time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"
copyright = "The Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/UNFmontreal/unf-montreal.ca"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/UNFmontreal/unf-montreal.ca"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"


[[params.versions]]
  version = "v0.3"
  url = "https://v0-3.kubeflow.org"

######################################################## END DOCSY ###########################################################


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://goo.gl/maps/1ZXgXqEoeuQTfeMP9"
map_latitude = "45.491178"
map_longitude = "-73.623335"
map_marker = "images/marker.png"

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "fab fa-facebook" # refer to https://fontawesome.com/icons/
# link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # refer to https://fontawesome.com/icons/
link = "https://twitter.com/UNF_montreal"

[[params.social]]
title = "slack"
icon = "fab fa-slack" # refer to https://fontawesome.com/icons/
link = "http://mic-unf.slack.com/"

[[params.social]]
title = "github"
icon = "fab fa-github" # refer to https://fontawesome.com/icons/
link = "https://github.com/unfmontreal/"

# [[params.social]]
# title = "linkedin"
# icon = "fab fa-linkedin" # refer to https://fontawesome.com/icons/
# link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
about= "About"
# copyright
copyright = "Copyright &copy; 2020 UNF"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
home = "Accueil"
about= "À propos de nous"
# copyright
copyright = "Copyright &copy; 2020 UNF"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
